export const status = ["Available", "Not Available"];

export const regions = [
  "Ashanti",
  "Brong-Ahafo",
  "Central",
  "Eastern",
  "Greater Accra",
  "Northern",
  "Oti",
  "Savannah",
  "North East",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Western North",
  "Bono",
  "Ahafo",
];

export const countries = [
  "Benin",
  "Burkina Faso",
  "Cape Verde",
  "Ivory Coast (Côte d'Ivoire)",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Liberia",
  "Mali",
  "Mauritania",
  "Niger",
  "Nigeria",
  "Senegal",
  "Sierra Leone",
  "Togo",
];

const countriesWestAfrica = [
  {
    country: "Benin",
    regions: [
      "Alibori",
      "Atakora",
      "Atlantique",
      "Borgou",
      "Collines",
      "Donga",
      "Kouffo",
      "Littoral",
      "Mono",
      "Ouémé",
      "Plateau",
      "Zou",
    ],
  },
  {
    country: "Burkina Faso",
    regions: [
      "Boucle du Mouhoun",
      "Cascades",
      "Centre",
      "Centre-Est",
      "Centre-Nord",
      "Centre-Ouest",
      "Centre-Sud",
      "Est",
      "Hauts-Bassins",
      "Nord",
      "Plateau-Central",
      "Sahel",
      "Sud-Ouest",
    ],
  },
  {
    country: "Cape Verde",
    regions: ["Barlavento Islands", "Sotavento Islands"],
  },
  {
    country: "Gambia",
    regions: [
      "Banjul",
      "Central River",
      "Lower River",
      "North Bank",
      "Upper River",
      "West Coast",
    ],
  },
  {
    country: "Ghana",
    regions: [
      "Ashanti",
      "Brong-Ahafo",
      "Central",
      "Eastern",
      "Greater Accra",
      "Northern",
      "Oti",
      "Savannah",
      "North East",
      "Upper East",
      "Upper West",
      "Volta",
      "Western",
      "Western North",
      "Bono",
      "Ahafo",
    ],
  },
  {
    country: "Guinea",
    regions: [
      "Boke",
      "Conakry",
      "Faranah",
      "Kankan",
      "Kindia",
      "Labe",
      "Mamou",
      "Nzerekore",
    ],
  },
  {
    country: "Guinea-Bissau",
    regions: [
      "Bafata",
      "Biombo",
      "Bissau",
      "Bolama-Bijagos",
      "Cacheu",
      "Gabu",
      "Oio",
      "Quinara",
      "Tombali",
    ],
  },
  {
    country: "Ivory Coast",
    regions: [
      "Agnéby",
      "Bafing",
      "Bas-Sassandra",
      "Denguélé",
      "Gôh-Djiboua",
      "Lacs",
      "Lagunes",
      "Montagnes",
      "Sassandra-Marahoué",
      "Savanes",
      "Vallée du Bandama",
      "Worodougou",
      "Zanzan",
    ],
  },
  {
    country: "Liberia",
    regions: [
      "Bomi",
      "Bong",
      "Gbarpolu",
      "Grand Bassa",
      "Grand Cape Mount",
      "Grand Gedeh",
      "Grand Kru",
      "Lofa",
      "Margibi",
      "Maryland",
      "Montserrado",
      "Nimba",
      "River Cess",
      "River Gee",
      "Sinoe",
    ],
  },
  {
    country: "Mali",
    regions: [
      "Bamako",
      "Gao",
      "Kayes",
      "Kidal",
      "Koulikoro",
      "Mopti",
      "Segou",
      "Sikasso",
      "Tombouctou",
    ],
  },
  {
    country: "Mauritania",
    regions: [
      "Adrar",
      "Assaba",
      "Brakna",
      "Dakhlet Nouadhibou",
      "Gorgol",
      "Guidimaka",
      "Hodh Ech Chargui",
      "Hodh El Gharbi",
      "Inchiri",
      "Nouakchott",
      "Tagant",
      "Tiris Zemmour",
      "Trarza",
    ],
  },
  {
    country: "Niger",
    regions: [
      "Agadez",
      "Diffa",
      "Dosso",
      "Maradi",
      "Niamey",
      "Tahoua",
      "Tillabéri",
      "Zinder",
    ],
  },
  {
    country: "Nigeria",
    regions: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Federal Capital Territory",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
    ],
  },
  {
    country: "Senegal",
    regions: [
      "Dakar",
      "Diourbel",
      "Fatick",
      "Kaffrine",
      "Kaolack",
      "Kédougou",
      "Kolda",
      "Louga",
      "Matam",
      "Saint-Louis",
      "Sédhiou",
      "Tambacounda",
      "Thiès",
      "Ziguinchor",
    ],
  },
  {
    country: "Sierra Leone",
    regions: ["Eastern", "Northern", "Southern", "Western"],
  },
  {
    country: "Togo",
    regions: ["Centrale", "Kara", "Maritime", "Plateaux", "Savanes"],
  },
];
